CREATE TABLE IF NOT EXISTS `addresses` (
  `id`        	   INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `person`		       INT(11) DEFAULT NULL,
  `address1`	       VARCHAR(50) DEFAULT NULL,
  `address2`	       VARCHAR(50) DEFAULT NULL,
  `city`	         VARCHAR(50) DEFAULT NULL,
  `state`	         VARCHAR(50) DEFAULT NULL,
  `zipcode`	       VARCHAR(50) DEFAULT NULL,
  `datecreated` 	 TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `datemodified`   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `addresses` (`id`,`person`),
  FOREIGN KEY (person) REFERENCES persons(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
