version: '3.7'

services:
  myapi_db:
    image: linuxserver/mariadb
    container_name: myapi_db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=<yourdbpass>
      - TZ=Europe/London
      - MYSQL_DATABASE=demo
      - MYSQL_USER=demo
      - MYSQL_PASSWORD=demo
    volumes:
      - /Users/ciwise/Data/my-api/maria:/config
    restart: unless-stopped
  api:
    image: dlwhitehurst/my-api
    restart: always
    container_name: api
    ports:
      - 2000:80
    volumes:
      - ./:/www/api
    networks:
      - api
    links:
      - myapi_db 
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_NAME: demo
      DB_PASSWORD: demo

networks:
  api:
    driver: bridge
